-- genhdl\test_sample_hold/test_sample_hold.vhd
-- Generated by SystemVision VHDL Netlister 5.10.3 Update-1 (Build 2014.06.24)
-- File created Thu Apr 05 18:00:22 2018

library ieee;
library edulib;
library svlib;
use ieee.std_logic_1164.all;
use ieee.electrical_systems.all;
use ieee.mechanical_systems.all;
use ieee.fluidic_systems.all;
use ieee.thermal_systems.all;
use ieee.radiant_systems.all;
use work.all;

entity TEST_SAMPLE_HOLD is
end entity TEST_SAMPLE_HOLD;

architecture arch_TEST_SAMPLE_HOLD of TEST_SAMPLE_HOLD is
   terminal VIN: ELECTRICAL;
   signal Z0: REAL;
   signal Z1: REAL;
   signal Z2: REAL;
   signal CLK: STD_LOGIC;

begin

   \$1I1\ : entity WORK.SAMPLE_HOLD(DEFAULT)
      port map ( INPUT => VIN,
                CLK => CLK,
                OUTPUT => Z0 );

   \$1I23\ : entity WORK.ZDELAY(DEFAULT)
      generic map ( COUNT => 2 )
      port map ( INPUT => Z0,
                CLK => CLK,
                OUTPUT => Z2 );

   V_SINE1 : entity EDULIB.V_SINE(IDEAL)
      generic map ( AMPLITUDE => 1.0,
                    FREQ => 1.0 )
      port map ( POS => VIN,
                NEG => ELECTRICAL_REF );

   \$1I36\ : entity WORK.ZDELAY(DEFAULT)
      generic map ( COUNT => 1 )
      port map ( INPUT => Z0,
                CLK => CLK,
                OUTPUT => Z1 );

   CLOCK1 : entity EDULIB.CLOCK(IDEAL)
      generic map ( PERIOD => 20 MS )
      port map ( CLK_OUT => CLK );

end architecture arch_TEST_SAMPLE_HOLD;

