-- genhdl\test_sample_hold/test_sample_hold.vhd
-- Generated by SystemVision VHDL Netlister 5.10.3 Update-1 (Build 2014.06.24)
-- File created Thu Apr 12 15:30:22 2018

library ieee;
library edulib;
library svlib;
use ieee.std_logic_1164.all;
use ieee.electrical_systems.all;
use ieee.mechanical_systems.all;
use ieee.fluidic_systems.all;
use ieee.thermal_systems.all;
use ieee.radiant_systems.all;
use work.all;

entity TEST_SAMPLE_HOLD is
end entity TEST_SAMPLE_HOLD;

architecture arch_TEST_SAMPLE_HOLD of TEST_SAMPLE_HOLD is
   terminal \$1N48\: ELECTRICAL;
   signal X: REAL;
   signal LINC: REAL;
   terminal VIN: ELECTRICAL;
   signal Z0: REAL;
   signal INTX: REAL;
   signal Z1: REAL;
   signal Z2: REAL;
   terminal \$1N66\: ELECTRICAL;
   signal SQ: REAL;
   signal INTINTX: REAL;
   signal CLK: STD_LOGIC;

begin

   SH0 : entity WORK.SAMPLE_HOLD(DEFAULT)
      port map ( INPUT => VIN,
                CLK => CLK,
                OUTPUT => Z0 );

   Z1_1 : entity WORK.ZDELAY(DEFAULT)
      generic map ( COUNT => 2 )
      port map ( INPUT => Z0,
                CLK => CLK,
                OUTPUT => Z2 );

   VSINE : entity EDULIB.V_SINE(IDEAL)
      generic map ( AMPLITUDE => 1.0,
                    FREQ => 1.0 )
      port map ( POS => VIN,
                NEG => ELECTRICAL_REF );

   Z0_1 : entity WORK.ZDELAY(DEFAULT)
      generic map ( COUNT => 1 )
      port map ( INPUT => Z0,
                CLK => CLK,
                OUTPUT => Z1 );

   SH1 : entity WORK.SAMPLE_HOLD(DEFAULT)
      port map ( INPUT => \$1N48\,
                CLK => CLK,
                OUTPUT => SQ );

   CLK_1 : entity EDULIB.CLOCK(IDEAL)
      generic map ( PERIOD => 20 MS )
      port map ( CLK_OUT => CLK );

   LINC_1 : entity WORK.LINEARCOMBINATION(DEFAULT)
      generic map ( INITIAL => 0.0 )
      port map ( INPUTA => SQ,
                INPUTB => Z0,
                OUTPUT => LINC );

   VCLK : entity EDULIB.V_PULSE(IDEAL)
      generic map ( AC_MAG => 0.0,
                    PERIOD => 200 MS,
                    PULSE => 1.0,
                    WIDTH => 100 MS )
      port map ( POS => \$1N48\,
                NEG => ELECTRICAL_REF );

   INT0 : entity WORK.MYINT(DEFAULT)
      port map ( INPUT => X,
                CLK => CLK,
                OUTPUT => INTX );

   INT1 : entity WORK.MYINT(DEFAULT)
      port map ( INPUT => INTX,
                CLK => CLK,
                OUTPUT => INTINTX );

   VDC : entity EDULIB.V_CONSTANT
      generic map ( LEVEL => 1.0 )
      port map ( POS => \$1N66\,
                NEG => ELECTRICAL_REF );

   SH2 : entity WORK.SAMPLE_HOLD(DEFAULT)
      port map ( INPUT => \$1N66\,
                CLK => CLK,
                OUTPUT => X );

end architecture arch_TEST_SAMPLE_HOLD;

